### ISSUE TITLE
Implement an HR topography input in ClimatExML

### ISSUE THREAD

**Issue by nannau** [nannau/ClimatExML#2]
@kdaust has made a ton of progress using HR topography in the model architecture. It would be really nice to implement this in ClimatExML. We should use this issue to track/discuss design ideas for how exactly to implement it.

At a high level, I'm thinking we can specify some HR topography file that has been processed as a `.pt` file like what you would get from ClimatExPrep. We can then specify the location of that file in the `config.yaml` file and load somewhere in the pipeline.

It would make sense to load this file perhaps in the `loader.py` portion of the pipeline. Although, we should be careful that we aren't loading the same file over and over again. At a first glance, this might be the right function to add it to: https://github.com/nannau/ClimatExML/blob/c6e4c74bea22a60278fd113341df8e3bd209e949/ClimatExML/loader.py#L28.

**Comment by nannau** [comment]
Actually upon second glance, modifying this might do the trick: https://github.com/nannau/ClimatExML/blob/c6e4c74bea22a60278fd113341df8e3bd209e949/ClimatExML/loader.py#LL7C1-L18C24

Something like:
```python
class ClimatExMLLoader(Dataset):
    def __init__(self, lr_glob, hr_glob, topo_path) -> None:
        self.lr_glob = lr_glob
        self.hr_glob = hr_glob
        self.topo = torch.load(topo_path)

    def __len__(self):
        return len(self.lr_glob[0])

    def __getitem__(self, idx):
        lr = torch.stack([torch.load(var[idx]) for var in self.lr_glob])
        hr = torch.stack([torch.load(var[idx]) for var in self.hr_glob])     
        return [lr, hr, self.topo]

```

That way if I'm not mistaken, `topo` is loaded from file _once_ when the ClimatExMLLoader object is instantiated

**Comment by kdaust** [comment]
Starting working on this today - I think it's important that including HR covariates is optional, since it can increase memory requires substantially. I've created a separate Generator class for updated generator, and then I think we can just include a flag in the yaml config file if we want the HR covariates.

**Comment by nannau** [comment]
Sounds good to me. We could build it into a path so just be something like:

```yaml
data:
  lr_shape:
    - 1 # n_covariates
    - 64 # x size
    - 64 # y size
  hr_shape:
    - 1 # n_predictands
    - 512 # x size
    - 512 # y size
  files:
    hr_topo: "/path/to/topo.pt"
    lr_test:
      - /home/nannau/climatex/data/fire_vars/proc/test/pr/lr/*.pt

....
```
Then we can just check if `config["data"]["hr_topo"] is not None` and use the HR topo generator class you made instead of the other one.
